FROM python:3.11

WORKDIR /app

RUN pip install fastapi
RUN pip install 'uvicorn[standard]'
RUN pip install python-dotenv
RUN pip install 'defog[postgres]'

# defog requires pandas even though it doesn't install it as a dependency?
RUN pip install pandas 

COPY query-api.py /app

EXPOSE 8000

CMD ["uvicorn", "query-api:app", "--host", "0.0.0.0", "--port", "8000"]
